### ISSUE TITLE
Example of updating a file

### ISSUE THREAD

**Issue by sc250024** [gr2m/semantic-release-plugin-update-version-in-files#25]
# Description

Would you mind putting an example of how this plugin works? I think if you deeply understand how `semantic-release` works, it would be straightforward to figure out, but I'm only a casual user of the tool.

**Comment by gr2m** [comment]
I use the plugin quite a lot, for example here:
https://github.com/octokit/core.js/blob/7644b3d7c5ba36508625d24b679f719701cfa11a/package.json#L81-L103

Does that help as an example?

**Comment by sc250024** [comment]
@gr2m Thanks for the example! I meant more for the targeted files themselves; what should they look like? I understand that you use globbing to select the files you want to process, but what do the files `"pkg/*/version.*"` (for example) contain?

Maybe I misinterpreted this module. It sounded to me like you can select certain files which contain a version string of some sort, and when `semantic-release` is performed, those files will get a version bump. Suppose you have a file `metadata.yaml` in the root of your repository. When using this plugin, it sounded like it could do the following on release:

```diff
name: my-app
description: some useful widget
- version: v0.1.0
+ version: v0.2.0
```

Is that not correct?

**Comment by gr2m** [comment]
Ah sorry I misunderstood your question.

By default, the plugin is looking for the string `0.0.0-development` and replaces it with the current version. An example file with that placeholder is https://github.com/octokit/core.js/blob/7644b3d7c5ba36508625d24b679f719701cfa11a/src/version.ts

You can customize the placeholder by using the `placeholder` variable.

> Suppose you have a file `metadata.yaml` in the root of your repository. When using this plugin, it sounded like it could do the following on release:
> 
> ```diff
> name: my-app
> description: some useful widget
> - version: v0.1.0
> + version: v0.2.0
> ```

your `metadata.yml` file would look like this instead

```yml
name: my-app
description: some useful widget
version: 0.0.0-development
```

The replacement will take place right before publishing. The changes should not be pushed back to your repository

**Comment by sc250024** [comment]
@gr2m Perfect, thank you very much!
