### ISSUE TITLE
Can't install on Mac Os: Unsupported platform for inotify@1.4.6

### ISSUE THREAD

**Issue by charlax** [gr2m/semantic-release-plugin-update-version-in-files#8]
Hi there & thanks for this library!

I can't install on Mac Os:

```bash
% npm install --save=dev semantic-release-plugin-update-version-in-files
npm ERR! code EBADPLATFORM
npm ERR! notsup Unsupported platform for inotify@1.4.6: wanted {"os":"linux","arch":"any"} (current: {"os":"darwin","arch":"x64"})
npm ERR! notsup Valid OS:    linux
npm ERR! notsup Valid Arch:  any
npm ERR! notsup Actual OS:   darwin
npm ERR! notsup Actual Arch: x64

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/ca/.npm/_logs/2020-03-13T16_41_56_888Z-debug.log
```

**Comment by gr2m** [comment]
I do not think that dependency is coming from `semantic-release-plugin-update-version-in-files`. When I check out the repository and run npm install, inotify does not get installed

**Comment by charlax** [comment]
Kudos to https://stackoverflow.com/questions/41816384/unsupported-platform-for-inotify1-4-1-wanted-oslinux-archany -> I had a typo in my command (`--save=dev` instead of `--save-dev`).

🤦‍♂
